namespace: redis-chat-backend

redis:
  enabled: true
  version: 7.0
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 1000m
      memory: 1Gi

service:
  enabled: true
  port: 6379