namespace: redis-chat-backend

redis:
  enabled: true
  version: "7.0"
  resources:
    requests:
      cpu: 500m
      memory: 100Mi
      ephemeralStorage: 100Mi
    limits:
      cpu: 1000m
      memory: 500Mi
      ephemeralStorage: 500Mi

service:
  enabled: true
  port: 6379