{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "{{ .Release.Name }}-deploy"
  name: "{{ .Release.Name }}-deploy"
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-deploy"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-deploy"
    spec:
      containers:
      - image: brunoeas1/chat-backend:{{ .Values.deployment.version | quote }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy | quote }}
        name: chat-backend-1
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
          name: http
          protocol: TCP
{{- if .Values.deployment.environments }}
        env:
{{ toYaml .Values.deployment.environments | indent 10 }}
{{- end }}
        resources:
          limits:
            cpu: {{ .Values.deployment.resources.limits.cpu }}
            memory: {{ .Values.deployment.resources.limits.memory }}
            ephemeral-storage: {{ .Values.deployment.resources.limits.ephemeralStorage }}
          requests:
            cpu: {{ .Values.deployment.resources.requests.cpu }}
            memory: {{ .Values.deployment.resources.requests.memory }}
            ephemeral-storage: {{ .Values.deployment.resources.requests.ephemeralStorage }}
{{- if .Values.deployment.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.deployment.readinessProbe | indent 10 }}
{{- end }}
{{- if .Values.deployment.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.deployment.livenessProbe | indent 10 }}
{{- end }}
{{- end }}
{{- if .Values.deployment.startupProbe }}
        startupProbe:
{{ toYaml .Values.deployment.startupProbe | indent 10 }}
{{- end }}
{{- end }}